name: tcc
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: 3.0.5

dependencies:
  flutter:
    sdk: flutter

  qr_flutter: ^4.1.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  google_fonts: ^5.0.0
  table_calendar: ^3.0.9
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  sqflite: ^2.2.8+4
  validadores: ^1.0.5
  regexed_validator: ^2.0.0+1
  dio: ^4.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
